### ISSUE TITLE
Audio only plays smoothly when tab is active in Firefox Nightly 

### ISSUE THREAD

**Issue by ripdog** [audiocogs/flac.js#3] opened 2013-01-17 19:51 UTC
Playing a local flac file, audio is flawless until I switch tab. Afterwards, it skips so badly about 80-90% of the time it is silent. Plays smoothly again the moment I make the flac.js tab active again.

Running: Mozilla/5.0 (Windows NT 6.2; WOW64; rv:21.0) Gecko/20130116 Firefox/21.0 ID:20130116031003

**Comment by jussi-kalliokoski** [comment] 2013-01-18 05:10
Interesting. Confirmed on Firefox Aurora 22.0 on OS X.

Browsers clamp set{Timeout,Interval} to 1s in background tabs so that we can't buffer enough data using the old Audio Data API because it has write limits. We have a workaround for this, where the timer is actually in a worker that communicates the timer hits with the main thread, but apparently even the timers that are in workers get clamped now.

I'd say the most rational thing to do right now is nothing. No point in figuring out yet another hack to temporarily fix an API that is deprecated and will be replaced soon.

**Comment by jussi-kalliokoski** [comment] 2013-01-18 05:10
Oh and thanks for reporting, @ripdog !

**Comment by ripdog** [comment] 2013-01-18 05:12
Hey, thanks for responding! I wasn't sure there was anyone really watching
this project anymore! You said that the Audio Data API is getting replaced
soon, what's replacing it?

On Fri, Jan 18, 2013 at 6:10 PM, Jussi Kalliokoski <notifications@github.com

**Comment by jussi-kalliokoski** [comment] 2013-01-18 05:19
@ripdog The [Web Audio API](https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html). The Firefox guys are going full speed ahead implementing this stuff: https://bugzilla.mozilla.org/show_bug.cgi?id=779297 and WebKit already has an experimental implementation as well.

You can try out the current Firefox implementation by heading to about:config and setting the flag "media.webaudio.enabled" to true, then just create a new mozAudioContext(). Not sure if it can produce any actual sound yet.

**Comment by ripdog** [comment] 2013-01-18 05:23
So the API Mozilla was trumpeting a few months ago was their own
'standard', which is now being replaced with the W3C version?

On Fri, Jan 18, 2013 at 6:19 PM, Jussi Kalliokoski <notifications@github.com

**Comment by jussi-kalliokoski** [comment] 2013-01-18 05:25
@ripdog Well, they haven't exactly trumpeted the API, it was deprecated more than a year ago. ^^ But something like that.

Also, this is somewhat the same bug as ofmlabs/aurora.js#13

**Comment by ripdog** [comment] 2013-01-18 05:40
Oh, just my temporal memory playing tricks on me again. (I remember a very
trumpety Mozilla Hacks article not that long ago). Does this mean you have
plans to port flac.js (and the others, I guess) to the new API? And will
the new API alleviate the limits which cause this bug?

On Fri, Jan 18, 2013 at 6:25 PM, Jussi Kalliokoski <notifications@github.com

**Comment by devongovett** [comment] 2014-07-21 03:16
Closing this. Firefox supports the Web Audio API now, and is generally more stable.

**Closed as completed by devongovett** 2014-07-21 03:16 UTC
